# Site settings
title: Ayhan Kosan
email: ayhanxkosan@gmail.com
url: https://ayhankosan.github.io/portfolio
description: "Interdisciplinary Geographer passionate about the Geospatial Sector with a focus on Remote Sensing, Urban Planning, GIS and Cartography"
keywords: "Remote Sensing, GIS, Geography, Data Analysis"
skills: "Geographer - Data Analyst - Environmental Planner"
meta_author: Kosan Ayhan

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: Kosayh

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,128,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Ayhan Kosan
  location: Location
  social: Around the Web
  credit: jekyll-theme-freelancer

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
#  - title: twitter
#    url: http://twitter.com/jekyllrb
#  - title: facebook
#    url:
#  - title: stack-overflow
#    url: http://stackoverflow.com/questions/tagged/jekyll
#  - title: bitbucket
#    url: http://bitbucket.org/jekyll
  - title: linkedin
    url: https://www.linkedin.com/in/ayhan-kosan/

# Postal address (add as many lines as necessary)
address:
  - line: Time zone GMT-7 (PST)
  - line: San Francisco, CA 94109

# Credits content
#credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: /:categories/:year/:month/:day/:title/
